name: Deploy with Password (Temporary)

on:
  workflow_dispatch:
  push:
    branches:
      - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy with Password Auth
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}  # Add this to GitHub Secrets temporarily
          port: ${{ secrets.VPS_PORT }}
          timeout: 300s
          script: |
            set -e
            echo "🚀 Starting deployment..."
            
            cd ${{ secrets.VPS_PATH }}
            
            # Backup environment
            cp .env .env.backup
            
            # Pull latest changes
            git fetch origin
            git reset --hard origin/deploy
            
            # Install dependencies
            composer install --optimize-autoloader --no-dev --no-interaction
            npm ci && npm run build
            
            # Restore environment
            cp .env.backup .env
            
            # Laravel optimizations
            php artisan migrate --force
            php artisan optimize
            php artisan queue:restart
            
            # Set permissions
            chmod -R 775 storage bootstrap/cache
            
            # Cleanup
            rm -f .env.backup
            
            echo "✅ Deployment completed!"